apiVersion: v1
kind: Pod
metadata:
  name: httpbin-pod
  labels:
    app: httpbin-webservice
spec:
  containers:
    - name: httpbin
      image: kennethreitz/httpbin
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
