apiVersion: batch/v1
kind: Job
metadata:
  name: python-job
spec:
  template:
    spec:
      containers:
      - name: pyjob
        image: python
        command: ["python",  "--version"]
      restartPolicy: Never
  backoffLimit: 4
